// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import java.lang.reflect.InvocationTargetException;
import java.util.stream.Collectors;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import myfirstmodule.mybatis.StudentMapperRunner;
import myfirstmodule.proxies.Student;
import org.apache.commons.beanutils.BeanUtils;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Java_action_2 extends CustomJavaAction<java.util.List<IMendixObject>>
{
	public Java_action_2(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		return new StudentMapperRunner().selectByStudent(getContext()).stream().map(src -> {
			Student dst = new Student(this.context());
			try {
				BeanUtils.copyProperties(dst, src);
			} catch (IllegalAccessException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (InvocationTargetException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			return dst.getMendixObject();
		})
				.collect(Collectors.toList());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Java_action_2";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
