// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import org.apache.ibatis.jdbc.SQL;

public class Java_action extends CustomJavaAction<java.lang.String>
{
	private java.lang.String AgentCode;

	public Java_action(IContext context, java.lang.String AgentCode)
	{
		super(context);
		this.AgentCode = AgentCode;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return new SQL()
				.SELECT("c.CUST_NAME, c.CUST_CODE, a.AGENT_NAME, a.AGENT_CODE")
				.FROM("customer c")
				.INNER_JOIN("agents a")
				.WHERE("c.AGENT_CODE = a.AGENT_CODE")
				.WHERE(String.format("a.AGENT_CODE = '%s'", AgentCode)).toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "Java_action";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
